#! /bin/env python
# encoding=utf-8
# gusimiu@baidu.com
# 

import sys

if __name__=='__main__':
    while 1:
        l=sys.stdin.readline()
        if l =='' : break
        try:
            print l.decode('utf-8').encode('gb18030').strip('\n')
        except Exception:
            continue
