# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
MISC_PATH=$HOME/misc
export MISC_PATH 

PATH=$PATH:$MISC_PATH/tool
PYTHONPATH=$PYTHONPATH:$MISC_PATH/pygsm

export PATH

unset USERNAME

alias hi=history
alias hig='hi|grep'
alias gcl=~/lisp/gcl-2.6.7/bin/gcl
alias py=python
#alias hfs_stoff="/home/work/gusimiu/hadoop-client-stoff/hadoop/bin/hadoop fs"
#alias hfs_sz="/home/work/gusimiu/hadoop-client-szjjh/hadoop/bin/hadoop fs"

# screen dir.
#export SCREENDIR=$HOME/gsm-screen
