" gsm's vim profile.
se nocp nu
behave mswin
colo evening 
so $VIMRUNTIME/mswin.vim
syn on
se hlsearch

se cindent
se shiftwidth=4
se tabstop=4

se nobackup
se nowritebackup

" set term to linux.
" allow command shown in current window.
se term=linux

" set the current line hilight.
"highlight CursorLine cterm=NONE ctermbg=4 " blue
"set cursorline

function PythonBegin()
	call setline(1, "\#! /bin/env python")
	call setline(2, "\# encoding=utf-8")
	call setline(3, "\# author: nickgu ")
	call setline(4, "\# ")
	call setline(5, "")
    call setline(6, "if __name__=='__main__':")
    call setline(7, "    ")
	"call setpos('.', [0, 7, 4, 0])
endfunction

" set corresponding fold method and maximum level.
se foldmethod=indent
au Filetype cpp se foldmethod=syntax
se foldlevel=1000

filetype off " vundle required
se expandtab
se smarttab
au Filetype python se formatoptions+=r
"au Filetype python se expandtab
"au FileType python se smarttab
au FileType python se fenc=utf-8
au BufNewFile *.py exec ":call PythonBegin()"

se nowrap

"se noexpandtab
se showcmd
se ruler
se wildmenu
se tags=./tags,tags,$HOME/rs/tags

" detection encoder order.
set fencs=ucs-bom,UTF-8,cp936,default,latin1
" encoder on file writer.
"set fenc=utf-8
" output buffer encoder.
set encoding=utf-8 

set list                
set listchars=tab:>-,trail:-

hi Macro ctermfg=red
hi Normal ctermfg=white
hi PreProc ctermfg=red

" deal with file diff.
map <C-J> [czz
map <C-K> ]czz
map <C-M> :diffg<CR>

map <C-N> :noh<CR>
"map <F10> :se enc=chinese<CR>
map <F6> :se fdm=syntax<CR>
map <F7> :se fdm=manual<CR>
map <F8> :%s/\r//g<CR>
" quickly switch window.
map <C-F> <C-W>w

map + gt
map _ gT

" make ctags in current directory recurrently.
map <F11> :!ctags -R --c++-kinds=+px --fields=iaS --extra=+q 

map <C-H> O//---------------------------  --------------------------<ESC>bhi
au Filetype python map <C-H> O##################################################<ESC>bhi

map <C-B> <C-Q>

" switch window and resize it max.
map <C-W>f <C-W>w<C-W>200+<C-W>200> 


" ==== VUNDLE PLUGIN SETTINGS ====
se rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'kien/ctrlp.vim'
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'


Plugin 'majutsushi/tagbar'
let g:tagbar_left=1
let g:tagbar_width = 30
let g:tagbar_iconchars = ['+', '-']
"au Filetype python TagbarOpen
"au Filetype cpp TagbarOpen
nmap <S-Q> :TagbarToggle<CR>

Plugin 'scrooloose/nerdtree'
let NERDTreeWinPos="right"
let NERDTreeWinSize=60
let NERDTreeIgnore=['\.d$[[dir]]', '\.o$[[file]]', '\.pyc$[[file]]']
nmap <S-A> :NERDTreeToggle<CR>
"autocmd vimenter * NERDTree

call vundle#end()
filetype plugin indent on  " vundle required

